name: "Deployment to GitHub Pages on Push"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - name: Install npm dependencies
        run: npm i

      - name: Build project
        run: npm run build-storybook

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./storybook-static" 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4